### ISSUE TITLE
Sick work FAM!

### ISSUE THREAD

**Issue by seanvree** [Kthulu120/liquid_dl#1]
Yo man, good work on this, looks dope. 

I'm honored to be the first PITA. 

OS:  windows 10E x64 1703
Python:  2.7.13

Error:

```
ImportError: No module named annoying.decorators
```

I've tried both localhost and a LAN IP and different ports just in case that was the issue. 

console output:

```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd c:\liquid_dl

c:\liquid_dl>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
Exception KeyboardInterrupt in <module 'threading' from 'C:\Python27\lib\threading.pyc'> ignored

c:\liquid_dl>python manage.py runserver localhost:8000
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x00000000049902E8>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Python27\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 26, in check_resolver
    return check_method()
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\liquid_dl\liquid_dl\urls.py", line 18, in <module>
    from liquid.views import schedule
  File "c:\liquid_dl\liquid\views.py", line 6, in <module>
    from annoying.decorators import ajax_request
ImportError: No module named annoying.decorators

c:\liquid_dl>python manage.py runserver 192.168.1.20:8010
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x0000000004C812E8>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Python27\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 26, in check_resolver
    return check_method()
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\liquid_dl\liquid_dl\urls.py", line 18, in <module>
    from liquid.views import schedule
  File "c:\liquid_dl\liquid\views.py", line 6, in <module>
    from annoying.decorators import ajax_request
ImportError: No module named annoying.decorators
```

**Comment by Kthulu120** [comment]
Sorry I forgot to add the pip requirements to the initial first release but if you use the virtualenv name 'env' I have then all the needed dependencies should be in there. Or if you'd rather install them yourself use [this](https://github.com/Kthulu120/liquid_dl/blob/master/requirements.txt) that lists all the dependencies needed then you should be good. Both methods should resolve ImportError, let me know if either work and resolve this issue.

**Comment by seanvree** [comment]
Great that did it! Def include a list of dependancies.

**Comment by seanvree** [comment]
@Kthulu120 

Yeah man, I'm not too familiar w Django, and I'm sure you're still working on the config instructions...so no rush buddy. 

 I'm sure there's just some config VARs that need to be set, but this is where I am now


```
Using the URLconf defined in liquid_dl.urls, Django tried these URL patterns, in this order:
^admin/
^liquid-dl [name='home']
^ ^ffmpeg$ [name='ffmpeg']
^ ^ffmpeg-submit [name='ffmpeg_submit']
^ ^soundcloud-submit [name='soundcloud_submit']
^ ^wget-submit [name='wget_submit']
The current path, liquid_dl/, didn't match any of these.
```

Where is the liquid_dl.settings file? I see the settings.py file at /liquid_dl/liquid_dl , is that what I'm supposed to configure?

![image](https://user-images.githubusercontent.com/8906637/30058588-8c51d86a-91f0-11e7-9e57-34c086109a13.png)

**Comment by Kthulu120** [comment]
Your url is liquid_dl when it should be liquid-dl, should resolve your issue. Let me know if this solves your problem.

**Comment by seanvree** [comment]
sorry to be such a noob man, where do I set that variable?

![image](https://user-images.githubusercontent.com/8906637/30059049-53409780-91f2-11e7-841d-75b206d7b6c4.png)

**Comment by Kthulu120** [comment]
Found the bug
I forgot to comment out {% render_bundle %} in the latest release in the templates/home.html file and uncomment out the script for the 'newest_prod_build' therefore your going to have to do it yourself if you download this before version 1.0.3 is released(which will be released around 9PM CST).

**Comment by seanvree** [comment]
@Kthulu120  - no prob. I'll wait brother.

**Comment by seanvree** [comment]
@Kthulu120  

Hey buddy, I assume you didn't get around to updating the repo?

**Comment by Kthulu120** [comment]
@seanvree no because I'm releasing the youtube-do update today also but give me an hour and I'll do a minor release v1. 0.0.3 to fix that error you had.

**Comment by Kthulu120** [comment]
@seanvree the newest release should fix any issues that your having now
