### ISSUE TITLE
Starting server results in error

### ISSUE THREAD

**Issue by greglaprise** [Kthulu120/liquid_dl#16]
Whenever I start the application I get this error. I'm using Ubuntu 16.04 completed updated.

"Unhandled exception in thread started by <function wrapper at 0x7f78a05a9ed8>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/greg/liquid_dl/liquid_dl/urls.py", line 20, in <module>
    from liquid.views import schedule
  File "/home/greg/liquid_dl/liquid/views.py", line 13, in <module>
    from liquid.auth.usermanagement import update_password, create_new_cloudcmd_password
  File "/home/greg/liquid_dl/liquid/auth/usermanagement.py", line 7, in <module>
    from passlib.hash import pbkdf2_sha256
ImportError: No module named passlib.hash"

**Comment by Kthulu120** [comment]
pip install passlib, sorry this was due to my error in not including it the requirements.txt file nor the readme file

**Comment by greglaprise** [comment]
I install passlib and I get similar errors.
<img width="681" alt="liquid-dl error when running" src="https://user-images.githubusercontent.com/26013982/31055772-97fe0722-a68d-11e7-9294-649d521d1465.PNG">

**Comment by Kthulu120** [comment]
Let me know if the newest build from the master branch fixes your issue

**Comment by greglaprise** [comment]
Bingo! Works just fine! Thanks!
