### ISSUE TITLE
heroku deploy failed please check my log file 

### ISSUE THREAD

**Issue by nk932714** [Kthulu120/liquid_dl#21]
```
 !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.

			Detected buildpacks: Python,Node.js

			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order

-----> Python app detected

 !     Warning: Your application is missing a Procfile. This file tells Heroku how to run your application.

 !     Learn more: https://devcenter.heroku.com/articles/procfile

-----> Installing python-3.6.4

-----> Installing pip

-----> Installing requirements with pip

       Collecting youtube_dl (from -r /tmp/build_5382b37cea9cbf746852261f5381ffbf/nk932714-liquid_dl-be142cb/requirements.txt (line 1))

         Downloading youtube_dl-2018.1.21-py2.py3-none-any.whl (1.7MB)

       Collecting certifi==2017.7.27.1 (from -r /tmp/build_5382b37cea9cbf746852261f5381ffbf/nk932714-liquid_dl-be142cb/requirements.txt (line 2))

         Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)

       Collecting chardet==3.0.4 (from -r /tmp/build_5382b37cea9cbf746852261f5381ffbf/nk932714-liquid_dl-be142cb/requirements.txt (line 3))

         Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)

       Collecting Django==1.11.4 (from -r /tmp/build_5382b37cea9cbf746852261f5381ffbf/nk932714-liquid_dl-be142cb/requirements.txt (line 4))

         Downloading Django-1.11.4-py2.py3-none-any.whl (6.9MB)

       Collecting django-annoying==0.10.3 (from -r /tmp/build_5382b37cea9cbf746852261f5381ffbf/nk932714-liquid_dl-be142cb/requirements.txt (line 5))

         Downloading django_annoying-0.10.3-py2.py3-none-any.whl

       Collecting django-webpack-loader==0.5.0 (from -r /tmp/build_5382b37cea9cbf746852261f5381ffbf/nk932714-liquid_dl-be142cb/requirements.txt (line 6))

         Downloading django_webpack_loader-0.5.0-py2.py3-none-any.whl

       Collecting idna==2.6 (from -r /tmp/build_5382b37cea9cbf746852261f5381ffbf/nk932714-liquid_dl-be142cb/requirements.txt (line 7))

         Downloading idna-2.6-py2.py3-none-any.whl (56kB)

       Collecting imgurpython==1.1.7 (from -r /tmp/build_5382b37cea9cbf746852261f5381ffbf/nk932714-liquid_dl-be142cb/requirements.txt (line 8))

         Downloading imgurpython-1.1.7.tar.gz

       Collecting pytz==2017.2 (from -r /tmp/build_5382b37cea9cbf746852261f5381ffbf/nk932714-liquid_dl-be142cb/requirements.txt (line 9))

         Downloading pytz-2017.2-py2.py3-none-any.whl (484kB)

       Collecting requests==2.18.4 (from -r /tmp/build_5382b37cea9cbf746852261f5381ffbf/nk932714-liquid_dl-be142cb/requirements.txt (line 10))

         Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)

       Collecting urllib3==1.22 (from -r /tmp/build_5382b37cea9cbf746852261f5381ffbf/nk932714-liquid_dl-be142cb/requirements.txt (line 11))

         Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)

       Collecting passlib>=1.7.1 (from -r /tmp/build_5382b37cea9cbf746852261f5381ffbf/nk932714-liquid_dl-be142cb/requirements.txt (line 12))

         Downloading passlib-1.7.1-py2.py3-none-any.whl (498kB)

       Installing collected packages: youtube-dl, certifi, chardet, pytz, Django, django-annoying, django-webpack-loader, idna, urllib3, requests, imgurpython, passlib

         Running setup.py install for imgurpython: started

           Running setup.py install for imgurpython: finished with status 'done'

       Successfully installed Django-1.11.4 certifi-2017.7.27.1 chardet-3.0.4 django-annoying-0.10.3 django-webpack-loader-0.5.0 idna-2.6 imgurpython-1.1.7 passlib-1.7.1 pytz-2017.2 requests-2.18.4 urllib3-1.22 youtube-dl-2018.1.21

-----> $ python manage.py collectstatic --noinput

       Traceback (most recent call last):

         File "manage.py", line 22, in <module>

           execute_from_command_line(sys.argv)

         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line

           utility.execute()

         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute

           self.fetch_command(subcommand).run_from_argv(self.argv)

         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv

           self.execute(*args, **cmd_options)

         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute

           output = self.handle(*args, **options)

         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle

           collected = self.collect()

         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect

           handler(path, prefixed_path, storage)

         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 354, in copy_file

           if not self.delete_file(path, prefixed_path, source_storage):

         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 260, in delete_file

           if self.storage.exists(prefixed_path):

         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/files/storage.py", line 392, in exists

           return os.path.exists(self.path(name))

         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 50, in path

           raise ImproperlyConfigured("You're using the staticfiles app "

       django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.

 !     Error while running '$ python manage.py collectstatic --noinput'.

       See traceback above for details.

       You may need to update application code to resolve this error.

       Or, you can disable collectstatic for this application:

          $ heroku config:set DISABLE_COLLECTSTATIC=1

       https://devcenter.heroku.com/articles/django-assets

 !     Push rejected, failed to compile Python app.

 !     Push failed



```

**Comment by Kthulu120** [comment]
With Django your required to have a STATIC ROOT and/or STATIC URL in the settings if you want to serve them. So something such as 
`STATIC_URL = "/static/"` 
Should hopefully be fine if not try your heroku address as the STATIC_ROOT. Let me know how tis effects your problem.

**Comment by Kthulu120** [comment]
Gonna go ahead close this issue, unless you need it reopened.
